Fixed other languages link in Hebrew translated README file, and changed a bit the look of the languages link in all translated files except Portugues
nukeop/nuclear pull request #845
Opened 2021-02-26 21:07 UTC by itayweb

2021-02-27 16:24 UTC, binarica requested changes

2021-02-27 16:24 UTC, binarica commented on docs/README-he.md
> +לפניכם רשימה של חבילות בשביל שימוש שונים, רובם נתמכות על ידי אדם צד שלישי. אנחנו רוצים להודות לתומכים על עבודתם.
I would phrase this differently, to emphasize the use for different package managers. Something like:
`לפניכם רשימה של החבילות עבור מנהלי החבילות השונים, רובן מתוחזקות על ידי תומכי צד שלישי`

2021-02-27 16:24 UTC, binarica commented on docs/README-he.md
> +מבינכם שמכירים את [mps-youtube](https://github.com/mps-youtube/mps-youtube), זו תוכנה דומה אך עם תוספת של ממשק משתמש גרפי. אנחנו מתמקדים בעיקר על השמע. דמיינו על ספוטיפיי אבל אתם לא צריכים לשלם עבורו
A couple of suggestions about מילות היחס:
`אנחנו מתמקדים בעיקר על השמע` -> `אנחנו מתמקדים בעיקר באודיו`
`דמיינו על ספוטיפיי` -> `דמיינו את ספוטיפיי`

And one about making the wording a bit more colloquial:
`אבל אתם לא צריכים לשלם עבורו` -> `אבל ללא תשלום`

2021-02-28 00:34 UTC, nukeop commented
Thanks for reviewing the change @binarica ! Please let me know when it's ready to merge.

2021-02-28 12:48 UTC, itayweb commented
> Thanks for reviewing the change @binarica ! Please let me know when it's ready to merge.

Fixed the words, the commit is ready to merge

2021-03-01 13:27 UTC, HaiDang666 commented
I think you should not commit package-lock.json and also rebase master branch to resolve the conflicts

2021-03-01 15:24 UTC, itayweb commented
> rebase master branch

When I added the changes it doesn't say that the package-lock.json file was changed, and what is rebasing master branch and how to do that?

2021-03-01 22:56 UTC, nukeop commented
Thanks, those little flags look very nice. I can let `package-lock.json` stay because it will have no net changes, but in the future please do not commit it. There are some merge conflicts but i think I will be able to resolve them manually. Thanks for contributing.

2021-03-01 22:59 UTC, merged

2021-03-02 06:15 UTC, itayweb commented
> Thanks, those little flags look very nice. I can let `package-lock.json` stay because it will have no net changes, but in the future please do not commit it. There are some merge conflicts but i think I will be able to resolve them manually. Thanks for contributing.

Alright, sorry for the troubles, I will do it next time