Favorite artist
nukeop/nuclear pull request #961
Opened 2021-05-31 09:38 UTC by HaiDang666

2021-06-21 22:16 UTC, nukeop requested changes

2021-06-21 22:16 UTC, nukeop commented on packages/ui/lib/components/ArtistGrid/index.tsx
> +export default compose(
Can you use hooks here instead of recompose HOCs? For new components, we should favor hooks unless strictly necessary.

2021-06-21 22:16 UTC, nukeop commented on packages/ui/lib/components/PopupDropdown/index.tsx
> +      // applyTriggerStyles={false}
Can you remove this line altogether? There is no such props on Dropdowns.

2021-06-21 22:16 UTC, nukeop commented on packages/app/app/components/ArtistView/index.tsx
> +                  name={isFavorite ? 'star' : 'star outline'}
Just noticed this recently that we have both stars and hearts for favorites. From now, let's just use hearts (and replace stars with hearts later).

2021-06-21 22:16 UTC, nukeop commented on packages/app/app/containers/ArtistViewContainer/ArtistViewContainer.test.tsx
> +  it('should add artist to favorites after clicking the star', async () => {
Replace star -> heart

2021-07-01 16:21 UTC, nukeop commented
I will resolve conflicts later today and merge your feature (unless you want to do that before me)

👍🏿  from me

2021-07-02 01:50 UTC, HaiDang666 commented
> I will resolve conflicts later today and merge your feature (unless you want to do that before me)
> 
> 👍🏿 from me

I gonna do it now 🚀

2021-07-02 03:35 UTC, merged